### PR TITLE
Fixed FireGento_Logger_Model_JsonStream logger

### PR DESCRIPTION
**Pull request by Fgruntjes**
The name of the class `FireGento_Logger_Model_Json` should be `FireGento_Logger_Model_JsonStream`.

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Thanks, Freek!

**Comment by Fgruntjes** [comment]
Great, thnx for merging.

When would you release a new version? This way we no longer have to depend on `dev-develop`.

**Comment by colinmollenhour** [comment]
Hey @daim2k5 I'm not sure what your release requirements are, perhaps you could draft a new release or let me know what to do or not to do?

**Comment by daim2k5** [comment]
We don't have any "release requirements" at the moment. If only bugfixes are applied we can draft a new release

**Comment by colinmollenhour** [comment]
It looks like you release by creating PR from dev to master so I added PR #113

**Comment by therouv** [comment]
@colinmollenhour @Fgruntjes @daim2k5 Just merged the PR into master and published an new release.

**Comment by Fgruntjes** [comment]
Thnx!

**Pull request merged**
