### PR TITLE
Added Extension Log Manager.

### PR DESCRIPTION
**Pull request by jayelkaake**
Added the Magento extension log manager that lets you shut off log output from modules you don't care about. Should automatically work. See the [Magento Log Manager extension on github here](https://github.com/jayelkaake/logmanager) for more info.

### CODE REVIEW

**Comment by daim2k5** [comment]
can you make the PR for the develop branch please?

**Comment by airbone42** [comment]
Should we really merge this into the firegento-logger? I think a hint in the README would be good to keep the modules decoupled. So we don't have to maintain upgrades and people who don't need this feature have less code to take care of.

**Comment by daim2k5** [comment]
Its strong related to logging and we have also a Feature Request for this see #62

**Comment by datenbrille** [comment]
Very interesting idea, but we should offer some events to do that and register a flag in the event to stop logging it. Therefor the logmanager can easily hook into the system. What do you think?

**Comment by jayelkaake** [comment]
I added native support for this extension now in the latest master of https://github.com/jayelkaake/logmanager
Just install firegento logger, then install log manager and it will work perfectly together.
I'll close this pull request now.

**Pull request closed without merging**
