### PR TITLE
Add Sentry.io support

### PR DESCRIPTION
**Pull request by colinmollenhour**
Sentry has a really great PHP support and this PR integrates it nicely into Magento including proper exception handling for `Mage::logException` as proper exceptions objects with previous exceptions and not just as a string message.

Also some other improvements were made in the process so a lot of other files were touched:

- Less duplication of event data collection when multiple targets are enabled
- Don't render backtrace as string unless it is actually used in a log message
- Added abstract to reduce duplicated code
- Amount of event data collected for "Simple" log messages reduced significantly
- Fix admin user id added to data
- Fix flaw causing `getEventDataArray` being called many times
- Move the "disabled modules" code to Queue model so it can be effective for all targets and DRY
- Fix "disabled modules" for "core" modules
- Add a "requestId" property so that multiple events can be easily correlated to the same request

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Add support for Javascript error handling via Sentry.io as well.

**Comment by Schrank** [comment]
Thanks for the PR. I can'T remember why, but we decided in the past to not add sentry to the core repo but instead wrote an extension: https://github.com/magento-hackathon/LoggerSentry

What about pushing the changes there?

Although I'm fine merging it. Any opinions on that? @therouv @daim2k5 @riconeitzel ?

**Comment by colinmollenhour** [comment]
Ahh, I wasn't aware of the extension! First commit in 2013! Perhaps a link should be added to the README?

I haven't compared the two implementations, but this PR makes a couple minor changes that would probably break the other one and I don't know if they'd have some other incompatibilities.. So probably should just close this PR.

**Review by daim2k5 — APPROVED** [review]

**Comment by sprankhub** [comment]
@kkrieger85, you wrote most of the Sentry extension. Any opinions on this PR?

**Comment by kkrieger85** [comment]
> @kkrieger85, you wrote most of the Sentry extension. Any opinions on this PR?

I didn't.

**Comment by Schrank** [comment]
Done, thanks for your patience :-)

**Pull request merged**
